### ISSUE TITLE
Definition of Clock Control Status Register

### ISSUE THREAD

**Issue by joergber** [dbuezas/arduino-web-timers#10]
Hi,

many thanks for your very helpful work!
It's also a very good tool to train somebody.

Within arduiono-web-timers scripts, the definition of the Clock Control Status Register is 'TCKSCR'.
Within your lgt8fx arduino board package it is 'TCKCSR'.

I agree, the definition in the data sheet is confusing ;)

Gruß
Jörg

**Comment by dbuezas** [comment]
Thank you for reporting this Jörg!
It's fixed now and I'll release it soon.
