### ISSUE TITLE
Windows-10 PC, Firefox browser , up/down slider for timer compare value not working

### ISSUE THREAD

**Issue by hmeijdam** [dbuezas/arduino-web-timers#2]
Let me start by saying ...Wow, wow and wow about the elegance of this tool. I think this will help a lot of people, also as a learning tool to grasp what timers actually do. 
You asked for some feedback, and the only thing I found for now is that I can use Chrome or Opera as a browser to have the slider working. My Firefox browser won't let me use the slider  for setting the OCRxA/B value(s).
This on a Windows10 PC.

**Comment by dbuezas** [comment]
Thanks! both for the bug report and the kind words :).
Fixed now, OCR handles now work in firefox.

**Comment by hmeijdam** [comment]
Confirmed, it's working fine now on Firefox (and Opera, Chrome and Edge also fine).

**Comment by dbuezas** [comment]
Thanks for trying it in all the other browsers! 🥇
