### ISSUE TITLE
TC0 dead time register issue

### ISSUE THREAD

**Issue by LaZsolt** [dbuezas/arduino-web-timers#25]
When I played with arduino-web-timers, I noticed the Timer 0 dead time can only be adjusted to maximum 15. I looked out why.
So I noticed the generated code has a bug.
```
  TCCR0A = 
    1 << COM0A1 |
    1 << COM0B1 |
    1 << WGM00;
  TCCR0B = 
    1 << DTEN0 |
    1 << CS00;
  DDRD = 
    1 << DDD5 |
    1 << DDD6;
  OCR0A = 59;
  OCR0B = 110;
  DTR0L = 11;   <-- There are no independent DTR0L and DRT0H registers
  DTR0H = 9;
```
`  DTR0 = (9 << 4 | 11) is (9 * 16 + 11) is (155)`

I think the correct setting of the Timer 0 DTR0 register for the example above is:
`  DTR0 = 155;`

https://dbuezas.github.io/arduino-web-timers/#mcu=LGT8F328P&timer=0&DeadTime=on&DTR0H=9&DTR0L=11&OCR0B=110&OCR0A=59

**Comment by dbuezas** [comment]
Oh right, I probably implemented dead time for 16 bit timers first (where there are independent low and high bytes). I think writing it down as you did, and formatting it as it's done with the bits in other registers is best. i.e:

```cpp
DTR0 = 
    9 << 4 |
    11;
```

I'll look into it soon, thanks for the issue.

**Comment by dbuezas** [comment]
I added an exception in the code to handle this case specifically. Not the most elegant solution but it gets the job done.

<img width="217" alt="image" src="https://user-images.githubusercontent.com/777196/219478263-9bb74f6e-8c3a-4ce5-9566-b0c0fa96154a.png">

**Comment by dbuezas** [comment]
I just realized I'm doing the low half-byte first. Do you think it's more intuitive the other way around?

**Comment by LaZsolt** [comment]
Does not matter. It is good in this way.
(It's could have been much funnier swap the two half byte.)

**Comment by dbuezas** [comment]
Oh, yes hehe. Internally the halves are called DTR0H and L, so it's easy to see which to shift

**Comment by dbuezas** [comment]
pssssst, check out the [latest version](https://github.com/dbuezas/arduino-web-timers/pull/31)
The code is pretty now :)

**Comment by dbuezas** [comment]
It was bothering me a lot that the frequency and period calculations were off due to float precision. Now they are computed using fractional math so it is exact.

**Comment by LaZsolt** [comment]
> The code is pretty now :)

Really pretty. Congrat!
