### ISSUE TITLE
Error compiling code on Arduino IDE when using Dead time on timer 3

### ISSUE THREAD

**Issue by navr32** [dbuezas/arduino-web-timers#3]
Hello many thanks for this wonderfull timer configurator.
I do some try.
The pinout is quiet difficult to find the real pin .. perhaps add arduino pin number or physical of lgt qfp48 and 32 ???

I have want to put Dead time on timer 3 with pcpwm mode but at build time 
this report not valid in this scope...

I have try same setting for timer 3 with FPWM mode this build ok.

My device is wavgat avga328p clone minipro.
Have a nice day.

**Comment by dbuezas** [comment]
Thanks for reporting the bug and suggestion @navr32 !

### Regarding the compilation bug

* which Arduino core are you using?
* would you send me the configurations that don't compile? **(just copy and paste the url after configuring)**

### Regarding the suggestion of adding arduino pin and physical

* I agree... What do you think about showing it as a tooltip like this:
![image](https://user-images.githubusercontent.com/777196/124988801-c0aba280-e03e-11eb-9863-59a5a18117a8.png)
* If you find it intuitive, let me know and I'll take this info from the datasheet and fill all tooltips
* I also tried adding more checkboxes to select the pin number or arduino name, but the UI gets too bloated

**Comment by navr32** [comment]
Yes Very good idea to add on tooltips because you are right the UI become bloated...like you said it have so many option on this timers ..

void setup(){
  /* https://dbuezas.github.io/arduino-web-timers/#mcu=LGT8F328P&timer=3&timerMode=PCPWM&DeadTime=on&OCR3A=51&OCR3B=102&DTR3L=128&DTR3H=128 */
  noInterrupts();
  TCCR3A = 
    1 << COM3A1 |
    1 << COM3B1 |
    1 << WGM30;
  TCCR3B = 
    1 << CS30;
  TCCR3C = 
    1 << DTEN3;
  OCR3A = 51;
  OCR3B = 102;
  DTR3L = 128;
  DTR3H = 128;
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  interrupts();
}



void loop() {
  // put your main code here, to run repeatedly:

}
*****************************
the errors are on 
'DTR3L' was not dectest:16:3: 
error: 'DTR3H' was not declared in this scopelared in this scope

and so..

**Comment by dbuezas** [comment]
Oh, I see. The dead time constants are not defined yet in the core. I'll make a new rrlease in a week or two.
It will be a bit different in the 8 bit timers, each dead time is only 4 bytes wide so I'll add bit shifting and a single assignment to DTR.
Thanks for the report!
I'll ping you here when that's done

**Comment by dbuezas** [comment]
In the title you write "not valid in this scope". Do you mean "in this core" or "in this code?"

**Comment by navr32** [comment]
this is just the error message of the compiler on the arduino-ide..So perhaps i have to be more accurate for tittle..

**Comment by navr32** [comment]
Yes  thanks ! goodiest..

**Comment by dbuezas** [comment]
Should be now solved in the released v1.0.7 of the arduino core
