### ISSUE TITLE
timer 0: Dead time constants missing in core 

### ISSUE THREAD

**Issue by navr32** [dbuezas/arduino-web-timers#4]
Hi again . with timer 0 any output and build failed on all mode
if i set the dead time with lgt328

**Comment by dbuezas** [comment]
Thanks for this one also!
I'll need a bit more infos:
* What arduino core are you using?
* Please configure the timers and copy and paste the app url here

**Comment by navr32** [comment]
Hello   I use the lgt8fx 1.0.6 from dbuezas  arduino ide 1.8.10
void setup(){
  /* https://dbuezas.github.io/arduino-web-timers/#mcu=LGT8F328P&timer=0&DeadTime=on&OCR0A=51&OCR0B=102&DTR0L=8&DTR0H=8 */
  noInterrupts();
  TCCR0A = 
    1 << COM0A0 |
    1 << COM0B0 |
    1 << WGM00;
  TCCR0B = 
    1 << DTEN0 |
    1 << CS00;
  OCR0A = 51;
  OCR0B = 102;
  DTR0L = 8;
  DTR0H = 8;
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  interrupts();
}


void loop() {
  // put your main code here, to run repeatedly:

}
*****************************************************************
test:14:3: error: 'DTR0L' was not declared in this scope
   DTR0L = 8;

and so and so.. but ok with others timers.

**Comment by dbuezas** [comment]
Same issue as in #3

**Comment by dbuezas** [comment]
This should now be fixed in v1.0.7 of the arduino core
