### ISSUE TITLE
Adding a Frequency source setting 

### ISSUE THREAD

**Issue by navr32** [dbuezas/arduino-web-timers#8]
This will very good to add an input for set the  frequency source of timer that the graph use to displays the event and to have the timing on the graphic scale numbers to be able to see the timming event like
the "real world" case of the board... 16Mhz board..8mhz... or for some special case with some quartz with special frequencies very very less usual but sometime very interesting to have the microcontrollers to "BPM" exactly to this special frequencies...
So if done many time will be win with web timer to have the goods settings to have the timer good real life timing found...

**Comment by dbuezas** [comment]
Hey @navr32, I can do that but only with a list of frequencies.
I'm thinking about taking all available in the lgt core and these for atmel:
* 1MHz, 8Mhz (I think both are available with the internal oscillator) 
* 16MHz, 20Mhz (typical 5v external clock, and max possible)

What do you think?

**Comment by dbuezas** [comment]
As a note, the F_CPU is already encoded in the data matrix, I just need to add other options and all the maths should update automatically at run time

**Comment by navr32** [comment]
Yes i Think this very good idea. 


De: "David Buezas" ***@***.***> 
À: "dbuezas/arduino-web-timers" ***@***.***> 
Cc: "nicolas" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Vendredi 20 Janvier 2023 01:02:05 
Objet: Re: [dbuezas/arduino-web-timers] Adding a Frequency source setting (#8) 





As a note, the F_CPU is already encoded in the data matrix, I just need to add other options and all the maths should update automatically at run time

**Comment by dbuezas** [comment]
Released now!
