### ISSUE TITLE
Timer2 isuue

### ISSUE THREAD

**Issue by BochiPluis11** [dbuezas/arduino-web-timers#9]
Hello! Thanks for your software...
In Normal Mode (ATmEga328P), when select TOGGLE on OCA/B the code are

  TCCR2A = 
    1 << COM2A1 |
    1 << COM2B1;
  TCCR2B = 
    1 << CS22 |
    1 << CS21 |
    1 << CS20;
But must be  1 << COM2A0 |
                      1 << COM2B0;
Best regards...

**Comment by dbuezas** [comment]
Thank you!
Also fixed in #13 
It was also affecting other modes I hadn't tested for timer 0 and 2 in both platform.
